services:
  postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config:/config

  redis:
    image: redis:7-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config:/config
    environment:
      - CONFIG_PATH=/config/local.yaml

  auth-service:
    image: acyushka/vcj-auth-service:latest
    ports:
      - "8087:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config:/app/config
    environment:
      - GIN_MODE=debug
      - CONFIG_PATH=/app/config/local.yaml
      - JWT_PRIVATE_KEY=-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIO25XcFzX8NGODMYkTTLY6vgPV0A37HWW6gukxJoVaJfoAoGCCqGSM49\nAwEHoUQDQgAEQy0TSI95s6hkPCFyicGS8oVoAzB7yiQhjrsy9KV4QivobyYsb89Y\nxM7BJ+HHGhL83+DcKwRViLm3SlMV6NP/IQ==\n-----END EC PRIVATE KEY-----
      - JWT_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQy0TSI95s6hkPCFyicGS8oVoAzB7\nyiQhjrsy9KV4QivobyYsb89YxM7BJ+HHGhL83+DcKwRViLm3SlMV6NP/IQ==\n-----END PUBLIC KEY-----

volumes:
  postgres_data:
  redis_data:
